### PR TITLE
Sidebar

### LINKED ISSUE #1: [COMPONENT] - Sidebar
Create a sidebar navigation component for the webapp (see the mockup in the readme).

@harsimrat99 Feel free to populate this with more specifics of what you'd like.

- [x] Create component (visually, activation functionality)
- [x] #4

### PR DESCRIPTION
**Pull request by iWebster28**
closes #1 #2 #4

### CODE REVIEW

**Review by harsimrat99 — APPROVED** [review]

**Comment by harsimrat99** [comment]
@JLefebvre55 should we merge this PR? It seems to be a draft PR.

**Comment by JLefebvre55** [comment]
@harsimrat99 I think it's still in progress from what I can tell. @iWebster28 will mark it as a full PR when it's complete

**Comment by iWebster28** [comment]
Completed

**Review by JLefebvre55 — CHANGES_REQUESTED** [review]
@iWebster28 encountered an error:
Screen Shot 2021-07-10 at 12 32 28 AM
Maybe change lines 2 and 3 of App.js to use lowercase imports? Did yours compile properly?

**Comment by JLefebvre55** [comment]
> Maybe change lines 2 and 3 of App.js to use lowercase imports? Did yours compile properly?

Lol that fixed it

**Review by JLefebvre55 — APPROVED** [review]

**Comment by iWebster28** [comment]
Oh @JLefebvre55 I renamed all our components to use uppercase letters

**Comment by JLefebvre55** [comment]
@iWebster28 the files on my end were lowercased

**Comment by JLefebvre55** [comment]
They are on git too

Screen Shot 2021-07-10 at 12 40 42 AM

**Comment by iWebster28** [comment]
Should we stick with these conventions? https://reactjs.org/docs/faq-structure.html

**Comment by JLefebvre55** [comment]
@iWebster28 Absolutely - so long as GitHub keeps them capitalized on commit

**Comment by iWebster28** [comment]
Okay, yes I hadn't capitalized the test cases yet. Will do next

**Review by harsimrat99 — APPROVED** [review]

**Pull request merged**
