### PR TITLE
Device Register Page

### PR DESCRIPTION
**Pull request by iWebster28**
Partially addresses #8, adding the device registration page, with removal of the legacy API key field. Current fetches use localhost.

### CODE REVIEW

**Review by harsimrat99 — COMMENTED** [review]
Hi Ian. Thank you very much for making the register and unregister pages :). I was just wondering if you could please provide unit tests for the React components?

**Comment by harsimrat99** [comment]
@iWebster28 I am also noticing that upon running npm start the following error appears:

image

**Comment by iWebster28** [comment]
Hi @harsimrat99 I will get to work on fixing this issue, I will likely merge in the device branch into this one, which fixes the Unregister.js issue. I will also write the unit tests.

**Comment by harsimrat99** [comment]
No problem. Thank you Ian.

**Comment by iWebster28** [comment]
You can see the device page in d182564d822eeb48280bcbd0860582379686c190. Still need to fix some styles and add tests.

**Comment by iWebster28** [comment]
Added tests for Register page.

**Review by harsimrat99 — APPROVED** [review]

**Comment by harsimrat99** [comment]
Hi @iWebster28 . Thank you for making the tests for the device register page. I will proceed and close this branch now.

Best,
Harsimrat

**Pull request merged**
